// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentACar.Data;

namespace RentACar.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RentACar.Core.Models.Araba", b =>
                {
                    b.Property<int>("ArabaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EhliyetSinifi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KoltukSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UretimYili")
                        .HasColumnType("int");

                    b.Property<string>("YakitTuru")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArabaID");

                    b.ToTable("Araba");

                    b.HasData(
                        new
                        {
                            ArabaID = 1,
                            EhliyetSinifi = "B",
                            KoltukSayisi = 5,
                            Marka = "Tofaş",
                            Model = "Doğan",
                            Plaka = "43HD101",
                            UretimYili = 1995,
                            YakitTuru = "Benzin"
                        },
                        new
                        {
                            ArabaID = 2,
                            EhliyetSinifi = "B",
                            KoltukSayisi = 5,
                            Marka = "Tofaş",
                            Model = "Şahin",
                            Plaka = "43HD102",
                            UretimYili = 1995,
                            YakitTuru = "Benzin"
                        },
                        new
                        {
                            ArabaID = 3,
                            EhliyetSinifi = "B",
                            KoltukSayisi = 5,
                            Marka = "Tofaş",
                            Model = "Kartal",
                            Plaka = "43HD103",
                            UretimYili = 1995,
                            YakitTuru = "Benzin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
